name: Create release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Retrieve version + create release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Retrieve version
      id: version
      run: |
        version=$(ruby -e 'require "./lib/yajp/gem_version.rb"' -e 'puts Yajp::VERSION')
        echo "TAG_NAME=$version" >> $GITHUB_ENV
        latest_tag=$(git describe --tags --abbrev=0)
        git log --pretty='format:%h %s' ${latest_tag}..HEAD > release_notes.txt

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ env.TAG_NAME }}" \
          --title "v${{ env.TAG_NAME }}" \
          --notes-file release_notes.txt
