name: Create release

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    name: Retrieve version + create release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Retrieve version
      id: version
      run: |
        version=$(ruby -e 'require "./lib/yajp/gem_version.rb"' -e 'puts Yajp::VERSION')
        echo "TAG_NAME=$version" >> $GITHUB_ENV
        latest_tag=$(git describe --tags --abbrev=0)
        echo $latest_tag
        changes=$(git log --pretty='format:%h %s' ${latest_tag}..HEAD)
        echo $changes
        echo "::set-output name=description::$changes"

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: v${{ env.TAG_NAME }}
        body: ${{ steps.version.outputs.description }}
        draft: true
